# Generated by Django 4.1.13 on 2024-10-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0002_plante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('gravite', models.CharField(choices=[('Léger', 'Léger'), ('Modéré', 'Modéré'), ('Sévère', 'Sévère')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='prevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptômes_connexes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_préventives', to='plant_disease.symptome')),
            ],
        ),
    ]
