# Generated by Django 4.1.13 on 2024-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0003_symptome_prevention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptome',
            name='gravite',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
