# Generated by Django 4.1.13 on 2024-10-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_disease', '0004_alter_symptome_gravite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptome',
            name='gravite',
        ),
    ]
